### ISSUE TITLE
Default config is loading before desired config

### ISSUE THREAD

**Issue by dan-bowerman** [ramp4-pcar4/story-ramp#108]
If I attempt to load a specific StoryRAMP product, such as http://localhost:8080/#/en/410b88da-0ed1-4749-903f-5e76c24e2e5f, the default "00000000-0000-0000-0000-000000000000" loads for a second before the normal one starts loading.

If this one turns out to be complex, I would recommend we just gut 00000000-0000-0000-0000-000000000000 to be absolutely bare bones with no text so the "overwriting" isn't noticeable to the end user.

**Comment by RyanCoulsonCA** [comment]
Looks like this is due to us setting the config to `00000000-0000-0000-0000-000000000000` by default before loading in the config from the URL, as can be seen [here](https://github.com/ramp4-pcar4/story-ramp/blob/master/src/components/story/story-ramp.vue#L39). The default config shows up until the real config file is successfully fetched. 

Two proposed solutions:
1. As stated in the issue, we can gut the default config to have no text in it, although I'm not 100% how screen readers would react to all of the content changing.
2. We can hold off on displaying StoryRAMP immediately and instead display a loading spinner while the config is loaded. Something sort of similar to how the RAMP viewer loads.

I'm leaning more toward option 2 here because the amount of time it takes to load the config file will depend on how quickly it can be fetched from the server. If the server is slow then we should probably let the user know that the app is loading instead of just handing them a blank page.
