### ISSUE TITLE
Resolve issue with legends not expanding by default

### ISSUE THREAD

**Issue by dan-bowerman** [ramp4-pcar4/story-ramp#16]
Legends expand to open automatically when the map is loaded, if stated in the map configuration.

DanB: Is this still an issue? Is there an existing RAMP3 issue to link?

**Comment by dan-bowerman** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/StoryRAMP-61810f925832ab001db602b8/issues/ramp4-pcar4/story-ramp/16?planning-poker) with ZenHub @JahidAhmed @RyanCoulsonCA @yileifeng

**Comment by RyanCoulsonCA** [comment]
This is still a problem and is a [bug within RAMP3](https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3911). I can reproduce this using the `index-many.html` sample page in the RAMP3 repo using the StoryRAMP config files. I've been doing a bunch of investigating surrounding this issue and it appears to be related to the symbology animation service (it doesn't occur anymore if I remove the animation part of the code, but that also prevents symbology from opening at all so that's not a solution for this). 

The issue doesn't pop up every time which means we could also be dealing with a race condition somewhere, but it's hard to track down exactly where that could be occurring. I'm still looking into this issue and will post more updates as I find them.
