### ISSUE TITLE
Back button is blocking UI elements

### ISSUE THREAD

**Issue by dan-bowerman** [ramp4-pcar4/story-ramp#255]
![image](https://user-images.githubusercontent.com/5294596/199966493-5b99385f-fc67-4fe3-9806-1ce19244a53a.png)
![image](https://user-images.githubusercontent.com/5294596/199966639-90d93285-cf3a-455a-9005-abe5e4687697.png)

I'm open to solutions, I don't have any bright ideas for this. The new Back button, introduced to replicate AGOL functionality with dynamic slides/panels, is blocking key UI elements such as Geosearch or the datagrid.

I'm afraid we don't have enough runway left to consult the UI/UX Team on this one. 

This task is to resolve the issue of the Back button blocking UI elements in RAMP, covering parts of multimedia, etc.

**Comment by RyanCoulsonCA** [comment]
I've made the button text a bit smaller and reduced the padding a bit so it takes up less space. As far as the positioning of the button goes, I have a couple of options below. If anyone has any other ideas, feel free to post them below as well.

- Option A: Move the button to the bottom of the dynamic panel instead. If we have a dynamic panel that includes a map with a time slider we probably shouldn't go with this solution because this will most likely conflict.

![image](https://user-images.githubusercontent.com/25874602/199995650-78918e8f-3bde-410d-a417-365f93580fc2.png)


- Option B: Move the button outside of the dynamic panel container. It will still appear on the right side, but above the panel instead. 

![image](https://user-images.githubusercontent.com/25874602/199995501-61a0a8c7-9bb0-426e-9664-6366445ea807.png)

- Option C: Don't have an image for this one, but we could move the back button somewhere in the left panel. Could place the button at the bottom of the content and center it.

**Comment by spencerwahl** [comment]
For option C I would have it at the top right of the left panel and have it follow scrolling until the next panel. It's more work than the other options but I think it'll make the most sense for UX.

**Comment by yileifeng** [comment]
I like the sound of what Spencer mentioned for option C so that would be my vote, plus we get to avoid any further map overlap issues (option A) or taking up unnecessary extra space - (the map title can also go here which might not look nice - option B)

**Comment by dan-bowerman** [comment]
I agree regarding Option A colliding with the timeslider - we don't have any specific examples where that would be a problem yet (our existing timeslider maps are not in dynamic panels that would require the Back button), but we don't want to run into the problem later either.

Option B is fine but I don't like the idea of making the "top" panel even smaller on a mobile view. 

If you guys are voting for Option C and feel comfortable with its layout (please consider the mobile experience as much as possible). We could potentially get the UX Team on this for a more permanent solution later on.

**Comment by RyanCoulsonCA** [comment]
I've implemented Option C which seems to work pretty well:

![7945wg8](https://user-images.githubusercontent.com/25874602/200022154-4793caf4-717c-48b5-9ec1-cbf0d8f03a68.gif)


For mobile, I made the button static on the page so it doesn't overlap anything.

Example: 
![image](https://user-images.githubusercontent.com/25874602/200021189-7855eac3-b3b6-4126-aacb-86928818e00f.png)


Still open to changes if anyone has any recommendations, including for the button styling.
