### ISSUE TITLE
Scrolling on mobile puts header out of view

### ISSUE THREAD

**Issue by yileifeng** [ramp4-pcar4/story-ramp#357]
Only accessible after scrolling back up.

![image](https://github.com/ramp4-pcar4/story-ramp/assets/31557789/51502163-36aa-4b5f-acb6-efca04632a51)

**Comment by RyanCoulsonCA** [comment]
I've done a bunch of testing on this, and it looks like this problem is only occurring with the Chrome mobile emulator. I've tested the main branch on my own phone, and have tested with a bunch of different mobile resolutions (not using the emulator) and the header seems to follow the page as expected.
