### ISSUE TITLE
Prompt for credentials when attempting to post basemap on RAMP 4 particulate matter page

### ISSUE THREAD

**Issue by agdemers** [ramp4-pcar4/story-ramp#382]
[ This is just a template. You can delete any section that does not apply to the issue. ]

## Description

While running a test script simulating multiple simultaneous users navigating the particulate matter page a  prompt eventually appears requesting credentials from the simulated user when the page attempts to load maps (see attached). To my knowledge this is a publicly accessible page that doesn't require credentials for accessing any of the page features, including third party map service.

The url in the credential prompt points to an outside (not government) address. Maybe the map service is throttling or suspicious of maps being repeatedly loaded by the particulate matter page, I don't know.    

## Environment

Client: jmeter selenium test script using Chrome 116 browser

## Screenshots

![image](https://github.com/ramp4-pcar4/ramp4-pcar4/assets/145382697/765c7423-7fe8-4398-80d4-6ed7a8a85c06)
![image](https://github.com/ramp4-pcar4/ramp4-pcar4/assets/145382697/b13b3198-5713-4d6c-a5ea-70db13492f6f)

## Steps to reproduce

Running my jmeter test script for multiple concurrent users

## Expected behavior

No prompt for credentials when loading any of the maps

## Actual behavior

Eventual prompt for credentials when the page loads the maps from third party service.

**Comment by dan-bowerman** [comment]
Hi @agdemers, 

What are the conditions your jmeter test script is running under? How many concurrent users? Does this issue re-occur or did it only happen once?

What appears to be happening is the basemap service (hosted externally by Naturally Resources Canada) appears to be throwing up a login prompt instead of serving a basemap tile graphic. There are a number of reasons this could occur:
1. There is/was a problem on one or more of NRCan's ArcGIS Server instances that are hosting the basemap. As this is an extremely popular and open service, I wonder if this issue was a one-off?
2. They have actually put one or more of NRCan's ArcGIS Server instances under password protection (unlikely).
3. The connection is being throttled due to too many attempts at access from the same source.
4. Something else?

**Comment by agdemers** [comment]
Hi @dan-bowerman,

Sorry I didn't mention the number of users when the bug was observed as it was a négligeable number -> 3 users total. 

I haven't tried to reproduce the issue since I observed it. I'll try again today, and there were no special conditions when the script was run.

**Comment by agdemers** [comment]
Hi @dan-bowerman,

I ran the script for over two hours this morning and did not reproduce the condition wherein simulated users where prompted for credentials to load a basemap. Perhaps it is just a one-off where something wasn't working properly or maybe it is a time of day issue where there my be additional congestion or something like that.

You mentioned that the resource providing the map is popular and used by other services or applications. I performed the test on Thursday of last week. This is just off the top of my head, but is it possible that the resource may have been had unusually congested if folks were tracking Hurricane Lee on the east coast on Thursday and Friday.

**Comment by dan-bowerman** [comment]
RAMP4 now provides for a basemap failover that would trigger if the default NRCan basemap is offline or sending back errors. The default "failover" is the Province and Territorial boundaries outline basemap, which is hosted from ECCC's ArcGIS servers.
