### ISSUE TITLE
Timesliders require update for RAMP4/Vue3

### ISSUE THREAD

**Issue by dan-bowerman** [ramp4-pcar4/story-ramp#390]
Timesliders are currently leveraged by the following products:
- [ ] https://environmental-maps.canada.ca/ramp-storylines/index-ca-en.html#/en/410b88da-0ed1-4749-903f-5e76c24e2e5f
- [ ] https://environmental-maps.canada.ca/ramp-storylines/index-ca-en.html#/en/4a99bbb4-7aba-49b2-8a84-f149a7b7bace
- [ ] https://environmental-maps.canada.ca/ramp-storylines/index-ca-en.html#/en/253s99wa-7pd8-4526-223f-8q37w49j2e4g
- [ ] https://environmental-maps.canada.ca/ramp-storylines/index-ca-en.html#/en/887dadc1-7936-4628-9c27-79da8da891ea
- [ ] https://environmental-maps.canada.ca/ramp-storylines/index-ca-en.html#/en/02980a8b-c041-49f9-9820-40bf05a75002
- [ ] https://environmental-maps.canada.ca/ramp-storylines/index-ca-en.html#/en/f6f7baf4-cccb-4521-a037-b4691b0f0d49
- [ ] https://environmental-maps.canada.ca/ramp-storylines/index-ca-en.html#/en/fee93703-c719-423a-86e2-abe30b992aa5

We require a timeslider feature that will work in RAMP4/Vue3 and supports the same basic look and feel as the existing ones. Ideally, the schema providing info to it will remain the same. 

NOTE: This timeslider may also work as the starting ground for upcoming CESI work, so may need to go into RAMP4 proper?

**Comment by james-rae** [comment]
Random ideas (especially if it ends up being in RAMP core): In RAMP4, making it look like it is now (horizontal bar running along the bottom) means it gets implemented as a map component. Any panels can then cover it. 

This is also true in RAMP2, but you can position it so that only a maximized grid covers it. In RAMP4, covering it is fairly easy; e.g. having a legend open and then doing an identify (== 3 panels).

- Maybe this is fine. All good.
- A fancy option that makes panels have 80% height instead of 100%. All panels should be handling vertical overflow anyways so this just changes the look, allows a slider to lurk in the under-part.
- Vertical slider in a panel.
  - Allows the slider to be minimized to the app bar.
  - Vertical layout removes the issue of label crowding on horizontal bar (especially in a mobile layout).
  - Would allow slider to be teleported. (Would be curious if this could allow a "horizontal" option that ends up looking good when teleported to a div under the map).
  - Could be argued that it doesn't look as nice is in the standard setting. Having the slider just "there" and in idealized presentation is eyecatching, especially on a site where time-slicing is a core part of the data.

Will defer to the experts in SpencerBar™ technology.
